### ISSUE TITLE
Update runtime to 5.15-22.08

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.onionshare.OnionShare#8]
OnionShare still seems to use the older 5.15-21.08 runtime. Please, consider updating it.

**Comment by mig5** [comment]
It's fixed in code, just hasn't been released yet. https://github.com/onionshare/onionshare/blob/c4d0b644648a98e79fa80340cb6960932cde008d/flatpak/org.onionshare.OnionShare.yaml#L4-L5

**Comment by firefoxlover** [comment]
still no release?

**Comment by dginovker** [comment]
#12 seems relevant

**Comment by trytomakeyouprivate** [comment]
Yes, I researched every latest tag (with many exceptions where packages had no new tags in years despite active commits), so this is still experimental though. If it would build that would be great, as nearly all packages are upgraded

**Comment by mig5** [comment]
Should be fixed as of https://github.com/onionshare/onionshare/releases/tag/v2.6.1

**Comment by Justinzobel** [comment]
It's been moved to Qt6 and there's a PR in for updating to the latest Qt6 runtime, this can be closed.
